apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: public
spec:
  selector:
    {{- toYaml .Values.gatewaySelector | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range $host, $_ := .Values.routes }}
        - {{ $host | quote }}
        {{- end }}
{{- range $host, $backend := .Values.routes }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $host | replace "." "-" }}
spec:
  hosts:
    - {{ $host | quote }}
  gateways:
    - public
  http:
    - route:
        - destination:
            host: {{ $backend }}
            port:
              number: 80
{{- end }}
